language: cpp
dist: trusty
sudo: required
matrix:
    include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
before_install:
  . deps.sh
  - if [[ -n $SCAN_BUILD ]]; then
      if [[ $TRAVIS_OS_NAME = "osx" ]]; then
        . scan-build-install.sh;
      else
        export SCAN_BUILD_PATH=scan-build;
      fi
    fi
before_script:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      if [ ! -z "$HOST" ]; then
        unset CC;
        unset CXX;
      fi
    fi
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      if [ -z "$COMPILER_CXX"]; then
        export CC=$COMPILER_CC;
        export CXX=$COMPILER_CXX;
      fi
    fi
script:
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .
  - $SCAN_BUILD_PATH make
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-5
      - g++-5
      - clang-3.6
      - cmake
