language: cpp
dist: trusty
sudo: required
compiler:
- gcc
- clang
os:
- linux
- osx
env:
- SCAN_BUILD=true
- SCAN_BUILD=false
- COMPILER_CC=gcc-5
- COMPILER_CXX=g++-5
install: make get-deps
before_install:
  - if [[ -n $SCAN_BUILD ]]; then
      if [[ $TRAVIS_OS_NAME = "osx" ]]; then
        . scan-build-install.sh;
      else
        export SCAN_BUILD_PATH=scan-build;
      fi
    fi
before_script:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      if [ ! -z "$HOST" ]; then
        unset CC;
        unset CXX;
      fi
    fi
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      if [ -z "$COMPILER_CXX"]; then
        export CC=$COMPILER_CC;
        export CXX=$COMPILER_CXX;
      fi
    fi
  - cmake .
script:
  - $SCAN_BUILD_PATH make
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-5
      - g++-5
      - clang-3.6
      - cmake
