language: cpp
dist: trusty
sudo: required
matrix:
    include:
    - compiler: gcc
      os: linux
      env: COMPILER=g++-5
    - compiler: clang
      os: linux
      env: COMPILER=clang++-3.7
    - compiler: gcc
      os: linux
      env: COMPILER=clang++-3.7
      env: SCAN_BUILD=true
    - compiler: clang
      os: osx
      env: COMPILER=clang
      env: SCAN_BUILD=true
before_install:
- . deps.sh
- if [[ -n $SCAN_BUILD ]]; then
    if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      . scan-build-install.sh;
    else
      export SCAN_BUILD_PATH=scan-build;
    fi
  fi
- if [[ $TRAVIS_OS_NAME = "osx" ]]; then
    - brew update
    - brew outdated libtool cmake || brew upgrade libtool cmake
  fi
script:
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .
  - $SCAN_BUILD_PATH make
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - gcc-5
      - g++-5
      - clang-3.7
      - clang-3.5
      - cmake
